version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - "/var/www/site/php:/var/www/myapp"
      - "/var/www/site/docker/site.conf:/etc/nginx/conf.d/site.conf"
      - "/var/www/site/php:/usr/share/nginx/html"
    depends_on:
      - php
      - mariadb
    links:
      - php

  php:
    image: php:8.1-fpm
    build:
      context: .        
      dockerfile: ./Dockerfile

    volumes:
      - "/var/www/site/php:/var/www/myapp"
      - "/var/www/site/docker/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - "mariadb-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "qwerty"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
